import type { CollectionConfig } from 'payload'
import { isAuthenticated, anyone } from '../payload/access'
import { makeRevalidateHooks } from '../payload/revalidate'

const revalidate = makeRevalidateHooks(['/blog', '/en/blog'])

export const CtaWidgets: CollectionConfig = {
  slug: 'cta-widgets',
  admin: {
    useAsTitle: 'name',
    defaultColumns: ['name', 'templateType', 'placement', 'isActive'],
    group: 'Content',
  },
  access: {
    read: anyone,
    create: isAuthenticated,
    update: isAuthenticated,
    delete: isAuthenticated,
  },
  hooks: {
    afterChange: [revalidate.afterChange],
    afterDelete: [revalidate.afterDelete],
  },
  fields: [
    { name: 'name', type: 'text', required: true },
    {
      name: 'templateType',
      type: 'select',
      required: true,
      options: [
        { label: 'Hero Banner', value: 'HERO_BANNER' },
        { label: 'Service Card', value: 'SERVICE_CARD' },
        { label: 'Inline Callout', value: 'INLINE_CALLOUT' },
        { label: 'Custom Image', value: 'CUSTOM_IMAGE' },
        { label: 'Minimal Strip', value: 'MINIMAL_STRIP' },
        { label: 'Floating Notification', value: 'FLOATING_NOTIFICATION' },
        { label: 'Split Visual', value: 'SPLIT_VISUAL' },
        { label: 'Counter Urgency', value: 'COUNTER_URGENCY' },
      ],
    },
    { name: 'heading', type: 'text' },
    { name: 'subheading', type: 'textarea' },
    { name: 'buttonText', type: 'text' },
    { name: 'buttonUrl', type: 'text', required: true },
    { name: 'secondaryButtonText', type: 'text' },
    { name: 'secondaryButtonUrl', type: 'text' },
    { name: 'backgroundImage', type: 'upload', relationTo: 'media' },
    { name: 'backgroundColor', type: 'text' },
    { name: 'textColor', type: 'text' },
    { name: 'cssClass', type: 'text' },
    { name: 'gaEventCategory', type: 'text' },
    { name: 'gaEventLabel', type: 'text' },
    { name: 'dataAttributes', type: 'json' },
    {
      name: 'placement',
      type: 'select',
      required: true,
      options: [
        { label: 'Inline', value: 'INLINE' },
        { label: 'Above Fold', value: 'ABOVE_FOLD' },
        { label: 'Below Article', value: 'BELOW_ARTICLE' },
        { label: 'Sidebar', value: 'SIDEBAR' },
        { label: 'Sticky Bottom', value: 'STICKY_BOTTOM' },
        { label: 'Between Paragraphs', value: 'BETWEEN_PARAGRAPHS' },
        { label: 'After TOC', value: 'AFTER_TOC' },
      ],
    },
    { name: 'paragraphIndex', type: 'number' },
    {
      name: 'targetingType',
      type: 'select',
      defaultValue: 'ALL_POSTS',
      options: [
        { label: 'All Posts', value: 'ALL_POSTS' },
        { label: 'Specific Posts', value: 'SPECIFIC_POSTS' },
        { label: 'By Tag', value: 'BY_TAG' },
        { label: 'By Category', value: 'BY_CATEGORY' },
        { label: 'Exclude Posts', value: 'EXCLUDE_POSTS' },
      ],
    },
    { name: 'targetPosts', type: 'relationship', relationTo: 'posts', hasMany: true },
    { name: 'targetTags', type: 'relationship', relationTo: 'tags', hasMany: true },
    { name: 'targetCategories', type: 'relationship', relationTo: 'categories', hasMany: true },
    {
      name: 'isActive',
      type: 'checkbox',
      defaultValue: true,
      admin: { position: 'sidebar' },
    },
    { name: 'startDate', type: 'date' },
    { name: 'endDate', type: 'date' },
    { name: 'showOnMobile', type: 'checkbox', defaultValue: true },
    { name: 'showOnDesktop', type: 'checkbox', defaultValue: true },
    { name: 'maxImpressions', type: 'number' },
    { name: 'dismissible', type: 'checkbox', defaultValue: true },
    { name: 'dismissDuration', type: 'number', defaultValue: 7 },
    { name: 'displayTrigger', type: 'text' },
    { name: 'displayDelay', type: 'number' },
    { name: 'scrollDepthThreshold', type: 'number' },
    { name: 'countdownLabel', type: 'text' },
    { name: 'imagePosition', type: 'text' },
    { name: 'emoji', type: 'text' },
    { name: 'sponsoredLabel', type: 'checkbox', defaultValue: false },
    { name: 'impressionCount', type: 'number', defaultValue: 0, admin: { readOnly: true } },
    { name: 'clickCount', type: 'number', defaultValue: 0, admin: { readOnly: true } },
  ],
}
