/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    posts: Post;
    categories: Category;
    tags: Tag;
    'case-studies': CaseStudy;
    industries: Industry;
    services: Service;
    testimonials: Testimonial;
    'cta-widgets': CtaWidget;
    'client-logos': ClientLogo;
    media: Media;
    'contact-submissions': ContactSubmission;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    industries: IndustriesSelect<false> | IndustriesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'cta-widgets': CtaWidgetsSelect<false> | CtaWidgetsSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titleId: string;
  titleEn?: string | null;
  /**
   * URL path. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * English URL slug
   */
  slugEn?: string | null;
  excerptId?: string | null;
  excerptEn?: string | null;
  /**
   * How you author the article body. "Rich text" uses the visual editor; "Markdown" lets you write/paste raw Markdown. The published article uses whichever is selected here.
   */
  bodyFormat?: ('richtext' | 'markdown') | null;
  bodyId?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Markdown source: headings (## / ###), lists, links, bold/italic, blockquotes, images, code.
   */
  bodyMarkdownId?: string | null;
  /**
   * Optional English translation, in Markdown.
   */
  bodyMarkdownEn?: string | null;
  featuredImage?: (number | null) | Media;
  featuredImageAlt?: string | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  metaTitleEn?: string | null;
  metaDescriptionEn?: string | null;
  ogImage?: (number | null) | Media;
  focusKeyword?: string | null;
  /**
   * auto-calculated
   */
  readingTime?: number | null;
  /**
   * auto-calculated
   */
  wordCount?: number | null;
  status: 'DRAFT' | 'REVIEW' | 'SCHEDULED' | 'PUBLISHED' | 'ARCHIVED';
  author: number | User;
  category?: (number | null) | Category;
  tags?: (number | Tag)[] | null;
  publishedAt?: string | null;
  scheduledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  folder?: ('general' | 'blog' | 'case-studies' | 'services' | 'team') | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    featured?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Author avatar shown on blog posts.
   */
  avatar?: (number | null) | Media;
  role?: ('ADMIN' | 'EDITOR' | 'VIEWER') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  nameId: string;
  nameEn?: string | null;
  /**
   * URL path. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * URL path. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  industry?: string | null;
  challenge?: string | null;
  strategy?: string | null;
  results?: string | null;
  thumbnail?: (number | null) | Media;
  service?: (number | null) | Service;
  titleId?: string | null;
  titleEn?: string | null;
  subtitleId?: string | null;
  subtitleEn?: string | null;
  summaryId?: string | null;
  summaryEn?: string | null;
  slugEn?: string | null;
  seoTitleId?: string | null;
  seoTitleEn?: string | null;
  seoDescId?: string | null;
  seoDescEn?: string | null;
  ogImage?: (number | null) | Media;
  featuredImage?: (number | null) | Media;
  durationLabel?: string | null;
  clientWebsite?: string | null;
  featured?: boolean | null;
  industryRel?: (number | null) | Industry;
  /**
   * URL path. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  clientName: string;
  clientLogo?: (number | null) | Media;
  author?: (number | null) | User;
  metrics?:
    | {
        metricLabel: string;
        beforeValue: string;
        afterValue: string;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  testimonial?: (number | null) | Testimonial;
  caseStudyServices?: (number | Service)[] | null;
  blocks?:
    | {
        blockType:
          | 'HERO'
          | 'OVERVIEW'
          | 'CLIENT_SNAPSHOT'
          | 'NARRATIVE'
          | 'METRIC_GRID'
          | 'TIMELINE'
          | 'CHART'
          | 'BEFORE_AFTER'
          | 'GALLERY'
          | 'VIDEO'
          | 'QUOTE'
          | 'SERVICES_USED'
          | 'RELATED_CASES'
          | 'CTA'
          | 'LEAD_FORM'
          | 'FAQ'
          | 'RICH_TEXT';
        sortOrder?: number | null;
        isVisible?: boolean | null;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  status: 'DRAFT' | 'REVIEW' | 'SCHEDULED' | 'PUBLISHED' | 'ARCHIVED';
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  name: string;
  /**
   * URL path. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  descriptionId: string;
  descriptionEn?: string | null;
  shortDescId?: string | null;
  shortDescEn?: string | null;
  /**
   * icon id or emoji
   */
  icon?: string | null;
  /**
   * Hex accent
   */
  color: string;
  funnelPosition?: string | null;
  sortOrder?: number | null;
  seoSchema?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  metaTitle?: string | null;
  metaDescription?: string | null;
  isActive?: boolean | null;
  pricingTiers?:
    | {
        tierName: string;
        priceLabel: string;
        priceValue?: number | null;
        features?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        isPopular?: boolean | null;
        sortOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  addOns?:
    | {
        name: string;
        description?: string | null;
        priceLabel?: string | null;
        isActive?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries".
 */
export interface Industry {
  id: number;
  nameId: string;
  nameEn?: string | null;
  /**
   * URL path. Auto-generated from the title if left blank.
   */
  slug?: string | null;
  /**
   * Hex color, e.g. #A855F7
   */
  accentColor?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  clientName: string;
  clientTitle: string;
  clientPhoto?: (number | null) | Media;
  quote: string;
  companyName: string;
  /**
   * Show on homepage
   */
  isHighlighted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-widgets".
 */
export interface CtaWidget {
  id: number;
  name: string;
  templateType:
    | 'HERO_BANNER'
    | 'SERVICE_CARD'
    | 'INLINE_CALLOUT'
    | 'CUSTOM_IMAGE'
    | 'MINIMAL_STRIP'
    | 'FLOATING_NOTIFICATION'
    | 'SPLIT_VISUAL'
    | 'COUNTER_URGENCY';
  heading?: string | null;
  subheading?: string | null;
  buttonText?: string | null;
  buttonUrl: string;
  secondaryButtonText?: string | null;
  secondaryButtonUrl?: string | null;
  backgroundImage?: (number | null) | Media;
  backgroundColor?: string | null;
  textColor?: string | null;
  cssClass?: string | null;
  gaEventCategory?: string | null;
  gaEventLabel?: string | null;
  dataAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  placement:
    | 'INLINE'
    | 'ABOVE_FOLD'
    | 'BELOW_ARTICLE'
    | 'SIDEBAR'
    | 'STICKY_BOTTOM'
    | 'BETWEEN_PARAGRAPHS'
    | 'AFTER_TOC';
  paragraphIndex?: number | null;
  targetingType?: ('ALL_POSTS' | 'SPECIFIC_POSTS' | 'BY_TAG' | 'BY_CATEGORY' | 'EXCLUDE_POSTS') | null;
  targetPosts?: (number | Post)[] | null;
  targetTags?: (number | Tag)[] | null;
  targetCategories?: (number | Category)[] | null;
  isActive?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  showOnMobile?: boolean | null;
  showOnDesktop?: boolean | null;
  maxImpressions?: number | null;
  dismissible?: boolean | null;
  dismissDuration?: number | null;
  displayTrigger?: string | null;
  displayDelay?: number | null;
  scrollDepthThreshold?: number | null;
  countdownLabel?: string | null;
  imagePosition?: string | null;
  emoji?: string | null;
  sponsoredLabel?: boolean | null;
  impressionCount?: number | null;
  clickCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Logos shown in the homepage "Trusted by" strip. The strip is hidden while this list is empty.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos".
 */
export interface ClientLogo {
  id: number;
  /**
   * Client / brand name (used as alt text).
   */
  name: string;
  /**
   * Transparent PNG or SVG works best.
   */
  logo: number | Media;
  /**
   * Optional link to the client website.
   */
  url?: string | null;
  isActive?: boolean | null;
  /**
   * Lower shows first.
   */
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  company?: string | null;
  phone?: string | null;
  services?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  budgetRange?: string | null;
  timeline?: string | null;
  message: string;
  source?: string | null;
  isRead?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'industries';
        value: number | Industry;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'cta-widgets';
        value: number | CtaWidget;
      } | null)
    | ({
        relationTo: 'client-logos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titleId?: T;
  titleEn?: T;
  slug?: T;
  slugEn?: T;
  excerptId?: T;
  excerptEn?: T;
  bodyFormat?: T;
  bodyId?: T;
  bodyEn?: T;
  bodyMarkdownId?: T;
  bodyMarkdownEn?: T;
  featuredImage?: T;
  featuredImageAlt?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaTitleEn?: T;
  metaDescriptionEn?: T;
  ogImage?: T;
  focusKeyword?: T;
  readingTime?: T;
  wordCount?: T;
  status?: T;
  author?: T;
  category?: T;
  tags?: T;
  publishedAt?: T;
  scheduledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nameId?: T;
  nameEn?: T;
  slug?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  industry?: T;
  challenge?: T;
  strategy?: T;
  results?: T;
  thumbnail?: T;
  service?: T;
  titleId?: T;
  titleEn?: T;
  subtitleId?: T;
  subtitleEn?: T;
  summaryId?: T;
  summaryEn?: T;
  slugEn?: T;
  seoTitleId?: T;
  seoTitleEn?: T;
  seoDescId?: T;
  seoDescEn?: T;
  ogImage?: T;
  featuredImage?: T;
  durationLabel?: T;
  clientWebsite?: T;
  featured?: T;
  industryRel?: T;
  slug?: T;
  clientName?: T;
  clientLogo?: T;
  author?: T;
  metrics?:
    | T
    | {
        metricLabel?: T;
        beforeValue?: T;
        afterValue?: T;
        sortOrder?: T;
        id?: T;
      };
  testimonial?: T;
  caseStudyServices?: T;
  blocks?:
    | T
    | {
        blockType?: T;
        sortOrder?: T;
        isVisible?: T;
        data?: T;
        id?: T;
      };
  status?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "industries_select".
 */
export interface IndustriesSelect<T extends boolean = true> {
  nameId?: T;
  nameEn?: T;
  slug?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  descriptionId?: T;
  descriptionEn?: T;
  shortDescId?: T;
  shortDescEn?: T;
  icon?: T;
  color?: T;
  funnelPosition?: T;
  sortOrder?: T;
  seoSchema?: T;
  metaTitle?: T;
  metaDescription?: T;
  isActive?: T;
  pricingTiers?:
    | T
    | {
        tierName?: T;
        priceLabel?: T;
        priceValue?: T;
        features?: T;
        isPopular?: T;
        sortOrder?: T;
        id?: T;
      };
  addOns?:
    | T
    | {
        name?: T;
        description?: T;
        priceLabel?: T;
        isActive?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  clientTitle?: T;
  clientPhoto?: T;
  quote?: T;
  companyName?: T;
  isHighlighted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cta-widgets_select".
 */
export interface CtaWidgetsSelect<T extends boolean = true> {
  name?: T;
  templateType?: T;
  heading?: T;
  subheading?: T;
  buttonText?: T;
  buttonUrl?: T;
  secondaryButtonText?: T;
  secondaryButtonUrl?: T;
  backgroundImage?: T;
  backgroundColor?: T;
  textColor?: T;
  cssClass?: T;
  gaEventCategory?: T;
  gaEventLabel?: T;
  dataAttributes?: T;
  placement?: T;
  paragraphIndex?: T;
  targetingType?: T;
  targetPosts?: T;
  targetTags?: T;
  targetCategories?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  showOnMobile?: T;
  showOnDesktop?: T;
  maxImpressions?: T;
  dismissible?: T;
  dismissDuration?: T;
  displayTrigger?: T;
  displayDelay?: T;
  scrollDepthThreshold?: T;
  countdownLabel?: T;
  imagePosition?: T;
  emoji?: T;
  sponsoredLabel?: T;
  impressionCount?: T;
  clickCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  url?: T;
  isActive?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        featured?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  phone?: T;
  services?: T;
  budgetRange?: T;
  timeline?: T;
  message?: T;
  source?: T;
  isRead?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  avatar?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  contactEmail?: string | null;
  whatsappNumber?: string | null;
  instagram?: string | null;
  address?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  contactEmail?: T;
  whatsappNumber?: T;
  instagram?: T;
  address?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}